### ISSUE TITLE
JSON Serializer: Writing a balanced reusable JSON serializer for resolver.

### ISSUE THREAD

**Issue by shameempk** [msg2shabeer/resolver#1]
SQLAlchemy objects are not directly serializable. Writing a serializer seems a good idea.

**Comment by shameempk** [comment]
This solution is quite old, but looks legit to me.
http://www.prschmid.com/2012/12/json-serializing-sqlalchemy-objects.html

**Comment by shameempk** [comment]
Issue is solved, will be closed once it is verified by team.

**Comment by msg2shabeer** [comment]
+1
nice work maan its working

**Comment by shameempk** [comment]
Closing till we find an issue with existing solution.
